(function () {

  /**
   * Example WonderPush website SDK plugin.
   * @class Example
   * @param {external:WonderPushPluginSDK} WonderPushSDK - The WonderPush SDK instance provided automatically on intantiation.
   * @param {Example.Options} options - The plugin options.
   */
  /**
   * @typedef {Object} Example.Options
   * @property {String} [hello] - The contents of the hello message. Defaults to "Hello, world!"
   */
  /**
   * The WonderPush JavaScript SDK instance.
   * @external WonderPushPluginSDK
   * @see {@link https://wonderpush.github.io/wonderpush-javascript-sdk/latest/WonderPushPluginSDK.html|WonderPush JavaScript Plugin SDK reference}
   */
  WonderPush.registerPlugin("example", {
    window: function (WonderPushSDK, options) {

      // Loads the stylesheet generated by the 'style.scss' file right next to this source file.
      WonderPushSDK.loadStylesheet('style.css');

      /**
       * A function that can be called through WonderPush like this: WonderPush.Plugins.get('example').sayHello()
       * In window context, this function displays a black square with the hello message specified in the options, defaulting to "Hello, world!"
       */
      this.sayHello = function() {
        var elt = document.createElement('div');
        elt.className = 'wonderpush-webplugin-example';
        elt.textContent = (options||{}).hello || "Hello, world!";
        elt.addEventListener('click', function() {
          document.body.removeChild(elt);
        });
        document.body.appendChild(elt);
      };
    },
    serviceWorker: function (WonderPushSDK, options) {
      /**
       * A function that can be called through WonderPush like this: WonderPush.Plugins.get('example').sayHello()
       * In the service worker context, this function logs to the console the hello message specified in the options, defaulting to "Hello, world!"
       */
      this.sayHello = function() {
        console.log((options || {}).hello || "Hello, world!");
      };
    },
  });
})();
